Feature/ins 2953
inperium-corp/inperium-openapi pull request #102
Opened 2020-11-20 10:10 UTC by fee1good

2020-12-01 16:01 UTC, aehrenthal requested changes

2020-12-01 16:01 UTC, aehrenthal commented on obs/obs-api.yaml
> +          multipart/form-data:
I think that the UI should just upload the import to the sell service and should not need to know about the OBS service. Additionally, the OBS service does not need to know about any custom sell business logic, I think all it should know about is storing any kind of file and retrieving them. The flow would be like this:
1. Send Excel + Mappings to the Sell Service
2. The Sell service uploads the file into the OBS server
3. The Sell service retrieves the file from the OBS server whenever it's ready to start a particular import
Otherwise, we implement custom import logic into a generic OBS service. I personally don't think it's very nice. @fee1good and @Zemidar what are your thoughts on this?

2020-12-03 14:25 UTC, fee1good commented on obs/obs-api.yaml
> +          multipart/form-data:
@aehrenthal 
So, the plan was to make OBS a single place where ALL files will be uploaded. And for the current implementation, OBS doesn't know anything about sell, it's just got the file, validate it and pass the Sell, where all logic is implemented

The only logic is the send the file to Sell, and we know it because we get the file on `/imports/` endpoint, if it will be `/import-talk/` then OBS send to talk

Using this way, we just skip `The Sell service uploads the file into the OBS server` which makes our service a bit faster and cleaner

2020-12-03 16:17 UTC, aehrenthal commented on obs/obs-api.yaml
> +          multipart/form-data:
@fee1good yes I agree that the OBS space should be the single place where all files will be uploaded. For me, it's more about how they are uploaded because now the OBS service needs to accept the mappings for the import at a special endpoint and in my opinion, the service should be "dumb" in a way that it doesn't even know about this custom logic of mappings for Sell. So all in all, I agree that the import files should be placed into the OBS service, I just think that the main entry point should be in Sell, which then places it into the OBS to make the OBS service unaware of mappings or custom Sell implementations. Let's discuss it on our team call we have shortly ok?

2020-12-04 09:12 UTC, Zemidar commented on obs/obs-api.yaml
> +          multipart/form-data:
@fee1good
Use OBS for all files download/upload/convert is absolutely right idea. On other hand OBS is internal service for other microservices and it's require some constraints like keeping OBS clear about any knowledge of Sell, Talk, etc.
What about change flow and remove mappings from OBS?

2020-12-04 15:02 UTC, aehrenthal commented on obs/obs-api.yaml
> +          multipart/form-data:
@Zemidar fully agree. What do you think @fee1good?

2020-12-07 08:25 UTC, BullDog57Rus commented on obs/obs-api.yaml
> +          multipart/form-data:
Just had a look at this discussion, and I agree with Alex and Dmitrii. I don't think that any of our common services should know about its clients (FE or any other BE)

2020-12-22 14:21 UTC, closed without merging