[INT-264] [BE] API Endpoint for "total calls" widget
inperium-corp/inperium-openapi pull request #103
Opened 2020-11-25 07:31 UTC by RockMother

2020-11-25 18:20 UTC, BullDog57Rus requested changes

2020-11-25 18:20 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +      parameters:
are all of the parameters required?

2020-11-25 18:20 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +        averageCallTime:
not REALLY sure, but maybe for consistency averageCallsTime. up to u :)

2020-11-25 18:20 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +        inboundDifference:
```suggestion
        inboundDelta:
```
I thing delta is the correct word when talking about difference over time

2020-11-25 18:20 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +      type: object
can you please add `required` for all of the fields in new models? we are using model generation of FE also, so it will make Evgeny's life much easier

2020-11-25 18:20 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +        totalTime:
millis? seconds?

2020-11-25 18:20 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +        time:
same here

2020-11-25 18:20 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +        missedCalls:
it is a bit inconsistent. inbound, outbound, inProgress, inQueue, but missedCalls. Either missed, or add calls everywhere :)

2020-11-25 20:01 UTC, RockMother commented on talk/talk-api.yaml
> +      parameters:
Done

2020-11-25 20:04 UTC, RockMother commented on talk/talk-api.yaml
> +      type: object
There are no required fields at the models.

2020-11-25 20:04 UTC, RockMother commented on talk/talk-api.yaml
> +        totalTime:
We use milliseconds over all API.

2020-11-25 20:07 UTC, RockMother commented on talk/talk-api.yaml
> +        missedCalls:
Done

2020-11-25 20:07 UTC, RockMother commented on talk/talk-api.yaml
> +        inboundDifference:
I think that delta is a more technical word, but the difference is more user friendly.

2020-11-26 09:18 UTC, BullDog57Rus approved these changes

2020-11-26 09:19 UTC, merged