INS-2994 Refactor Import process
inperium-corp/inperium-openapi pull request #113
Opened 2020-12-08 13:26 UTC by Zemidar

2020-12-08 14:09 UTC, olyavertwist commented on sell/sell-api.yaml
> +      parameters:
parameters:
        - name: mappings
          description: This parameter defines mapping between incoming data and Inperium Sell properties.
          in: query
          schema:
            type: string
        - name: linkToFile
          description: The link to the import file.
          in: query
          schema:
            type: string

2020-12-08 14:10 UTC, olyavertwist reviewed
I left a comment with descriptions

2020-12-08 14:45 UTC, aehrenthal requested changes

2020-12-08 14:45 UTC, aehrenthal commented on sell/sell-api.yaml
> -  /health:
Is the health endpoint no longer required? I think we use it to ping the server on a regular basis to ensure uptime.

2020-12-08 14:45 UTC, aehrenthal commented on sell/sell-api.yaml
> +        - name: linkToFile
```suggestion
        - name: fileUrl
```
I think we used "url" across the API to specify links. Just to be consistent.

2020-12-09 11:25 UTC, Zemidar commented on sell/sell-api.yaml
> -  /health:
Actually Spring Boot has own endpoint for this purpose - actuator/health
Who is responsible for ping server? I'll send him new endpoint :)

2020-12-09 11:28 UTC, Zemidar commented on sell/sell-api.yaml
> +        - name: linkToFile
Fixed

2020-12-11 15:05 UTC, RockMother approved these changes

2020-12-11 15:07 UTC, aehrenthal approved these changes

2020-12-11 15:08 UTC, merged

2020-12-11 15:11 UTC, aehrenthal commented on sell/sell-api.yaml
> -  /health:
Please ask @tsyrenov to change it in the AWS configs