New authentication implementation
inperium-corp/inperium-openapi pull request #115
Opened 2020-12-13 11:30 UTC by BullDog57Rus

2020-12-22 15:26 UTC, Zemidar approved these changes

2020-12-28 13:58 UTC, aehrenthal requested changes

2020-12-28 13:58 UTC, aehrenthal commented on obs/obs-api.yaml
> +  /files/uploadFromStarter:
I am not sure if this endpoint is perfectly named. I dont think the API should care whether or not the file comes from the starter library or in a different way. Can we maybe think of a better name to keep it more generic?

2020-12-31 13:30 UTC, BullDog57Rus commented on obs/obs-api.yaml
> +  /files/uploadFromStarter:
actually, it is a deprecated endpoint only to support talk roll from starter to microservice. We have to re-add all the files to the microservice

2020-12-31 13:30 UTC, BullDog57Rus commented on obs/obs-api.yaml
> +      summary: Readd the file uploaded by obs starter lib via the microservice
re-add? it's like repeating addition :D

2021-01-08 19:45 UTC, aehrenthal commented on obs/obs-api.yaml
> +        publiclyAccessible:
I think on the API level we can just do public as a boolean. In Spring it's a reserved keyword, so there it makes sense to use publiclyAccessible, but I think for the API it's nicer to just have a public boolean as we have for the other APIs such as admin/owner for the UserEntity.

2021-01-08 19:46 UTC, aehrenthal approved these changes

2021-01-08 21:16 UTC, merged