INT-310 Migrate from OBS starter to OBS microservice
inperium-corp/inperium-openapi pull request #125
Opened 2021-01-06 15:59 UTC by BullDog57Rus

2021-01-18 15:40 UTC, aehrenthal approved these changes

2021-01-19 11:17 UTC, evgeniyp requested changes

2021-01-19 11:17 UTC, evgeniyp commented on talk/talk-api.yaml
> -    get:
Frontend needs this feature. There are many places where FE receives only the audio file id and displays the Audio Player.

2021-01-19 14:17 UTC, BullDog57Rus commented on talk/talk-api.yaml
> -    get:
added :)

2021-01-19 14:29 UTC, evgeniyp approved these changes

2021-01-19 14:46 UTC, aehrenthal approved these changes

2021-01-19 16:39 UTC, merged