IBA-61: Added region to user & tenant mode and requests
inperium-corp/inperium-openapi pull request #132
Opened 2021-01-15 13:18 UTC by onlythenaive

2021-01-15 13:27 UTC, aehrenthal requested changes

2021-01-15 13:27 UTC, aehrenthal commented on hub/hub-api.yaml
> +          type: string
Shouldnt it be an Enum here too?

2021-01-15 13:27 UTC, aehrenthal commented on hub/hub-api.yaml
> +          type: string
Shouldnt it be an Enum here too?

2021-01-15 16:23 UTC, olyavertwist requested changes
Ilia, could you please add this description to all the instances of the region parameter (including User, UserRequest, UserAccountCreationRequest, etc. objects):

description: The target region of the user account. Inperium stores data in the datacenters on the account location in order to ensure the fastest access to data and its security.

2021-01-30 14:35 UTC, BullDog57Rus commented on hub/hub-api.yaml
> +          type: string
we'd better to move region to the whole component like `Region` and reuse it everywhere

2021-03-01 10:56 UTC, closed without merging