INS-3078 edit api
inperium-corp/inperium-openapi pull request #141
Opened 2021-02-14 09:54 UTC by fee1good

2021-02-14 22:17 UTC, aehrenthal requested changes

2021-02-14 22:17 UTC, aehrenthal commented on sell/sell-api.yaml
> +          content: {}
The description does not seem right

2021-02-16 13:25 UTC, Zemidar requested changes

2021-02-16 13:25 UTC, Zemidar commented on sell/sell-api.yaml
> +          description: The export started.
Please add some information about sending email after finished export process

2021-02-16 13:25 UTC, Zemidar commented on sell/sell-api.yaml
> +          content: {}
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/21361268/108068787-99ded680-7073-11eb-92f9-1bf57daa53e6.png">

2021-02-20 06:19 UTC, fee1good commented
Need approve pls for merge https://github.com/inperium-corp/inperium-server-sell/pull/979

2021-02-20 13:18 UTC, Zemidar approved these changes

2021-02-22 07:32 UTC, fee1good commented
@RockMother review pls 
![image](https://user-images.githubusercontent.com/16759866/108676444-44824980-74f9-11eb-850a-e312af28d398.png)

2021-02-22 11:25 UTC, RockMother approved these changes

2021-02-24 07:42 UTC, fee1good commented
![image](https://user-images.githubusercontent.com/16759866/108964763-f4d48700-768c-11eb-8b78-5d9966ad66a1.png)

@aehrenthal review pls

2021-02-24 12:33 UTC, aehrenthal requested changes

2021-02-24 12:33 UTC, aehrenthal commented on sell/sell-api.yaml
> +          description: The export started. Sending email link after finished export process.
```suggestion
          description: The export started. You will receive a download link via email when the export is finished.
```

2021-03-03 17:51 UTC, closed without merging