[INS-3192] [TECH] Separate communication methods into Phones and Emails
inperium-corp/inperium-openapi pull request #144
Opened 2021-02-16 15:51 UTC by RockMother

2021-02-16 17:04 UTC, aehrenthal requested changes

2021-02-16 17:04 UTC, aehrenthal commented on sell/sell-api.yaml
> +    Phone:
Can we please rename this to PhoneNumber?

2021-02-17 15:17 UTC, RockMother commented on sell/sell-api.yaml
> +    Phone:
Done

2021-02-17 16:42 UTC, aehrenthal approved these changes

2021-02-17 16:49 UTC, merged