Add an end-point to register new consumption of a feature
inperium-corp/inperium-openapi pull request #158
Opened 2021-03-07 20:31 UTC by eprudnikov

This draft shows a uniform interface to register the consumption of a feature. It's the uniform one because it encapsulates
- Update of the usage value if necessary
- Check whether the limit (if any) is exceeded
- Withdraw money from the balance if necessary

As a result, clients do not care about any limitation or price model the feature has.
The PR still lacks 
- Request model that will include at least quantity.
- Response model. Ideally, it should contain information about the current usage level and limit if they are set.

2021-03-08 15:13 UTC, aehrenthal requested changes
@eprudnikov I like the idea and concept behind this, very nice work. I assume we will still add some request body or additional parameters to attach additional information such as the quantity of the usage, etc.?

2021-03-08 15:13 UTC, aehrenthal commented on hub/hub-api.yaml
> +  /features/{anchor}/usage:
Would it be better to use usage or usages?
@Zemidar and @BullDog57Rus what do you think too?

2021-03-08 15:13 UTC, aehrenthal commented on hub/hub-api.yaml
> +        Use this endpoint to inform Hub about the consumption of the feature.
```suggestion
        Use this endpoint to inform the Hub about the consumption of a feature. 
```

2021-03-08 15:13 UTC, aehrenthal commented on hub/hub-api.yaml
> +          description: A unique anchor of feature.
```suggestion
          description: A unique anchor of the feature.
```

2021-03-08 17:09 UTC, Zemidar commented on hub/hub-api.yaml
> +  /features/{anchor}/usage:
As for me usages more suitable

2021-03-09 15:56 UTC, BullDog57Rus commented on hub/hub-api.yaml
> +  /features/{anchor}/usage:
I think usages makes more sense. And actually maybe it is better to add tenantId as a parameter somehow? Of course we always have the token of the tenant or we can override it using the API KEY. Just an idea

2021-03-14 20:22 UTC, eprudnikov commented
Thank you all for the feedback!
The main goal of this draft was to show an idea of the interface. I close it to rework [it based on the up-to-date API version](https://github.com/inperium-corp/inperium-openapi/pull/160). All your suggestions are included there.

2021-03-14 20:22 UTC, closed without merging