[INT-353] API to get/create/update features usage
inperium-corp/inperium-openapi pull request #160
Opened 2021-03-14 20:18 UTC by eprudnikov

It's a fair copy of [the previous PR about updating feature usage](https://github.com/inperium-corp/inperium-openapi/pull/158) (this time, it's based on the development branch). The PR still shows a uniform interface to register/update the consumption of a feature. It's the uniform one because it encapsulates
- Update of the usage value if necessary
- Check whether the limit (if any) is exceeded
- Withdraw money from the balance if necessary.

The main differences from the previous one are:
- The end-points are moved to /tenants/ path because they are about changing data related to the tenant.
- Now Hub supports not only increments of the usages but also setting the absolute value of it. It's necessary, for example, for Calls.
- Some fixes basing on the feedback are included.

Please note that it's still a draft. At least the following details to be added:
- Now tenants can have more than one subscription. 
- Add-ons can have their prices.
- Subscription can have more than one price (main product and add-ons).

It all should be reflected in this API.

@olyavertwist , I hope, the descriptions fit our common style.

2021-03-14 22:22 UTC, aehrenthal commented on hub/hub-api.yaml
> +      summary: Retrieve information about usage of a feature.
```suggestion
      summary: Retrieve information about the usage of a feature.
```

2021-03-14 22:22 UTC, aehrenthal commented on hub/hub-api.yaml
> +        Use this endpoint to get information about usage of a feature.
```suggestion
        Use this endpoint to get information about the usage of a feature.
```

2021-03-14 22:22 UTC, aehrenthal commented on hub/hub-api.yaml
> +      - Features
@olyavertwist will our documentation portal get confused with multiple tags or that should be fine?

2021-03-15 16:20 UTC, BullDog57Rus commented on hub/hub-api.yaml
> +      - Features
I am also wondering whether openapi generator will use it properly

2021-03-15 16:20 UTC, BullDog57Rus commented on hub/hub-api.yaml
> +          "*/*":
```suggestion
          application/json:
```

2021-03-15 16:20 UTC, BullDog57Rus commented on hub/hub-api.yaml
> +          "*/*":
```suggestion
          application/json:
```

2021-03-15 16:20 UTC, BullDog57Rus commented on hub/hub-api.yaml
> +        For example, you make internaltional call (in Inperium Talk) and the feature usage must be updated.
```suggestion
        For example, you make international call (in Inperium Talk) and the feature usage must be updated.
```

2021-03-15 16:20 UTC, BullDog57Rus commented on hub/hub-api.yaml
> +        isInfinite:
```suggestion
        infinite:
```
I think we try to stick to the idea of "booleans without prefixes", because they are quite understandable

2021-03-15 16:20 UTC, BullDog57Rus commented on hub/hub-api.yaml
> +          type: string
what is that? I think it will be an enum, right?

2021-03-15 16:20 UTC, BullDog57Rus commented on hub/hub-api.yaml
> +      description: The PlanFeature object describes the feature in the plan you have including consumed quantity, its limitation, etc.
```suggestion
      description: The FeatureUsage object describes the feature in the plan you have including consumed quantity, its limitation, etc. 
```

2021-03-15 18:40 UTC, eprudnikov commented on hub/hub-api.yaml
> +      - Features
The generator handles it correctly. It puts the end-points to the TenantController. 
Let me know if it confuses the portal. I'll leave only the Tenants tag then.

2021-03-15 18:41 UTC, eprudnikov commented on hub/hub-api.yaml
> +          "*/*":
That's a good point. Initially, I wrote it in that way, but then reworked because
- In other places we have "*/*"
- It forces clients to set the content type. For me, it is still okay but it should be consistent with other end-points.

2021-03-15 18:46 UTC, eprudnikov commented on hub/hub-api.yaml
> +          type: string
Yes, it should be definitely enum. I just decided to postpone this decision closer to the end of the work of the feature :)
Let me leave this discussion open as a reminder.

2021-03-22 09:15 UTC, olyavertwist commented on hub/hub-api.yaml
> +      summary: Retrieve information about usage of a feature.
Let's keep summaries short since they work as headers and don't add a dot. 
For example: Retrieve the feature usage

2021-03-22 09:17 UTC, olyavertwist commented on hub/hub-api.yaml
> +      - Features
I'm afraid having the same endpoint twice will make browsing API docs confusing (or probably break the whole thing, I'm not sure). Can we choose one tag?

2021-03-22 09:35 UTC, olyavertwist commented on hub/hub-api.yaml
> +      summary: Register a new usage of a feature.
summary: Register a feature usage
(no ending dot)

2021-03-22 09:42 UTC, olyavertwist commented on hub/hub-api.yaml
> +      summary: Update an amount of usage of a feature.
summary: Update the usage count
(Discussion point - amount is typically used with uncountable nouns. "usage" is quite uncountable but we somehow manage to count it, so we should probably say count instead of amount here)

2021-03-22 09:45 UTC, olyavertwist commented on hub/hub-api.yaml
> +        Use this endpoint to update the amount of consumption of a feature.
description: Use this endpoint to update the counter. If the feature consumption value overtops the previous one, the Hub will restrict the use of the feature or withdraw money from the tenant's balance.

2021-03-22 09:46 UTC, olyavertwist commented on hub/hub-api.yaml
> +        For example, you make internaltional call (in Inperium Talk) and the feature usage must be updated.
For example, you make an international call

2021-03-22 09:56 UTC, olyavertwist commented on hub/hub-api.yaml
> +            It depends on the end-point that is in use.
description: | 
            The number demonstrating how many times the feature was consumed. Depending on the endpoint that is in use, the quantity can be either the total feature usage count or its increment.

2021-03-25 13:05 UTC, BullDog57Rus commented on hub/hub-api.yaml
> +      - Tenants
I think we better change the tag to Features or Feature Usages

2021-03-25 14:26 UTC, aehrenthal commented on hub/hub-api.yaml
> +      - Tenants
Agreed

2021-04-03 14:20 UTC, aehrenthal commented on hub/hub-api.yaml
> +  /tenants/features/{anchor}/usages:
@eprudnikov, I would mark the other endpoints we wont use anymore as deprecated (such as the limits endpoint). Also, we need to create a task in Jira for the Sell and Talk team to upgrade their services on the backend to this new endpoint, ok?

2021-04-03 14:22 UTC, aehrenthal commented on hub/hub-api.yaml
>          discountAmount:
We also need to mark the "price" field as deprecated

2021-04-03 14:29 UTC, aehrenthal requested changes

2021-04-03 14:29 UTC, aehrenthal commented on hub/hub-api.yaml
> +            - ADDON
```suggestion
            - ADD_ON
```

2021-04-03 15:30 UTC, aehrenthal commented on hub/hub-api.yaml
> +    SubscriptionItem:
Seems like now we can only get the currency of the subscription by checking for the currency of the price in the subscription item. I think we need to add a readonly currency field to the SubscriptionEntity.

2021-04-07 19:01 UTC, eprudnikov commented on hub/hub-api.yaml
> +      summary: Retrieve information about usage of a feature.
Thank you for the suggestion. I updated the summary 👌

2021-04-07 19:03 UTC, eprudnikov commented on hub/hub-api.yaml
> +          "*/*":
Updated 👌

2021-04-07 19:03 UTC, eprudnikov commented on hub/hub-api.yaml
> +        For example, you make internaltional call (in Inperium Talk) and the feature usage must be updated.
Updated 👌

2021-04-07 19:05 UTC, eprudnikov commented on hub/hub-api.yaml
> +          type: string
Fixed ✔

2021-04-07 19:05 UTC, eprudnikov commented on hub/hub-api.yaml
> +      summary: Register a new usage of a feature.
Fixed ✔

2021-04-07 19:06 UTC, eprudnikov commented on hub/hub-api.yaml
> +        Use this endpoint to update the amount of consumption of a feature.
👌

2021-04-07 19:06 UTC, eprudnikov commented on hub/hub-api.yaml
> +            It depends on the end-point that is in use.
👌

2021-04-07 19:11 UTC, eprudnikov commented on hub/hub-api.yaml
> +        isInfinite:
Thanks Maxim. I'll keep it in mind. For now, the attribute is removed anyway.

2021-04-07 19:18 UTC, eprudnikov commented on hub/hub-api.yaml
> +  /tenants/features/{anchor}/usages:
For now I created [a task](https://blackbirdsoftware.atlassian.net/browse/IBA-104) for me to check whether the current interface supports all necessary scenarios. I expect that not all of them are covered so far.

2021-04-07 19:27 UTC, eprudnikov commented on hub/hub-api.yaml
> +    SubscriptionItem:
Since the API is not direct representation of the DB entities, we can keep all necessary attributes on the subscription level, if needed, without touching the entities. Let me leave the existing attribute `Subscription.Price` in place for now. It makes the interface compatible with the previous version and give the necessary currency without diving deep into the list of prices.
I have [a reminder](https://blackbirdsoftware.atlassian.net/browse/IBA-105) to discuss with you what information is needed by the UI. It's not the only consumer of the API, but the important one :)

2021-04-07 19:29 UTC, eprudnikov commented on hub/hub-api.yaml
>          discountAmount:
Please check [the comment below](https://github.com/inperium-corp/inperium-openapi/pull/160#discussion_r608977933). It can turn out that having price here can still be a good fit. We will discuss it.

2021-04-07 19:31 UTC, eprudnikov commented on hub/hub-api.yaml
> +      - Tenants
Yes, it makes sense. 
Changed ✔

2021-04-07 22:18 UTC, aehrenthal approved these changes

2021-04-07 22:24 UTC, merged