Bugfix/ins 3302/add create/update filters
inperium-corp/inperium-openapi pull request #180
Opened 2021-03-31 09:01 UTC by RockMother

2021-03-31 13:08 UTC, aehrenthal requested changes

2021-03-31 13:08 UTC, aehrenthal commented on sell/sell-api.yaml
> +        path:
As per the UI Sell PR, what does this do? :)

2021-04-01 01:07 UTC, aehrenthal requested changes

2021-04-01 01:07 UTC, aehrenthal commented on sell/sell-api.yaml
> +          description: The path to the data within the object.
```suggestion
          description: The path to access the data within the object.
```

2021-04-01 07:19 UTC, RockMother commented on sell/sell-api.yaml
> +          description: The path to the data within the object.
Fixed

2021-04-01 14:50 UTC, aehrenthal approved these changes

2021-04-02 09:55 UTC, merged