Global Registry API
inperium-corp/inperium-openapi pull request #190
Opened 2021-04-07 15:43 UTC by aehrenthal

This pull request moves the global registry API from the microservice into our OpenAPI repository. I also cleaned the API a bit by giving the models more precise and accurate names. Additionally, I added endpoints to update and delete the regional mappings for users, tenants and API keys.

2021-04-08 22:54 UTC, BullDog57Rus requested changes

2021-04-08 22:54 UTC, BullDog57Rus commented on global-registry/global-registry-api.yaml
> +  /regions/apiKeys:
is /regions prefix needed in all requests?

2021-04-08 22:54 UTC, BullDog57Rus commented on global-registry/global-registry-api.yaml
> +        - name: id
id of the region? or of the API key in GR service? I think for both, is better to be places in path

2021-04-08 22:54 UTC, BullDog57Rus commented on global-registry/global-registry-api.yaml
> +          "*/*":
```suggestion
          application/json:
```
and everywhere

2021-04-08 22:54 UTC, BullDog57Rus commented on global-registry/global-registry-api.yaml
> +        200:
```suggestion
        201:
```

2021-04-08 22:54 UTC, BullDog57Rus commented on global-registry/global-registry-api.yaml
> +        - name: id
same here, if it is the region id, then let's do /regions/{id}/tenants

2021-04-08 22:54 UTC, BullDog57Rus commented on global-registry/global-registry-api.yaml
> +        200:
```suggestion
        201:
```

2021-04-08 22:54 UTC, BullDog57Rus commented on global-registry/global-registry-api.yaml
> +        - name: id
see above, please

2021-04-08 22:54 UTC, BullDog57Rus commented on global-registry/global-registry-api.yaml
> +        200:
```suggestion
        201:
```

2021-04-08 22:54 UTC, BullDog57Rus commented on global-registry/global-registry-api.yaml
> +      properties:
required (I think all of them)

2021-04-08 22:54 UTC, BullDog57Rus commented on global-registry/global-registry-api.yaml
> +      properties:
required also

2021-04-08 22:54 UTC, BullDog57Rus commented on global-registry/global-registry-api.yaml
> +      properties:
let's add required to all paging responses also

2021-04-08 22:54 UTC, BullDog57Rus commented on global-registry/global-registry-api.yaml
> +      properties:
and here

2021-04-09 00:47 UTC, aehrenthal commented on global-registry/global-registry-api.yaml
> +  /regions/apiKeys:
No I guess we can remove them.

2021-04-09 00:49 UTC, aehrenthal commented on global-registry/global-registry-api.yaml
> +        - name: id
Agreed, this one shouldn't be there. I removed it, thanks!

2021-04-09 00:49 UTC, aehrenthal commented on global-registry/global-registry-api.yaml
> +          "*/*":
Thx, done

2021-04-09 00:50 UTC, aehrenthal commented on global-registry/global-registry-api.yaml
> +        - name: id
I removed it, it was not supposed to be there :)

2021-04-09 00:50 UTC, aehrenthal commented on global-registry/global-registry-api.yaml
> +        200:
Thx

2021-04-09 00:51 UTC, aehrenthal commented on global-registry/global-registry-api.yaml
> +        200:
Thx!

2021-04-09 00:51 UTC, aehrenthal commented on global-registry/global-registry-api.yaml
> +        - name: id
Fixed

2021-04-09 00:51 UTC, aehrenthal commented on global-registry/global-registry-api.yaml
> +        200:
Thx!

2021-04-09 00:52 UTC, aehrenthal commented on global-registry/global-registry-api.yaml
> +      properties:
I added the required check. Can you please just quickly explain me why we need a required check for a model that is not used as a request? Just curious :)

2021-04-09 00:52 UTC, aehrenthal commented on global-registry/global-registry-api.yaml
> +      properties:
Fixed

2021-04-09 00:53 UTC, aehrenthal commented on global-registry/global-registry-api.yaml
> +      properties:
Do you mean
```
      required:
        - paging
        - data
```
or
```
      required:
        - paging
```
Adding the 2nd one for now until your feedback.

2021-04-09 00:53 UTC, aehrenthal commented on global-registry/global-registry-api.yaml
> +      properties:
Done

2021-04-09 15:16 UTC, BullDog57Rus commented on global-registry/global-registry-api.yaml
> +      properties:
I mean the first option for all responses with pagination

2021-04-09 15:49 UTC, BullDog57Rus commented on global-registry/global-registry-api.yaml
> +      properties:
so we mark all not-nullable fields as required always. because in many requests we can have no field provided and do not want to mess the user's expectations

2021-04-09 18:06 UTC, aehrenthal commented on global-registry/global-registry-api.yaml
> +      properties:
Thanks! Just did that.

2021-04-10 11:49 UTC, BullDog57Rus approved these changes

2021-04-21 13:59 UTC, merged