INT-489 Missed Calls strategic vision
inperium-corp/inperium-openapi pull request #191
Opened 2021-04-07 23:16 UTC by BullDog57Rus

Fixed /calls filtering, added a custom filter for missed and no answer calls

2021-04-07 23:18 UTC, BullDog57Rus reviewed
@evgeniyp comments with non-back-compatible changes :)

2021-04-07 23:18 UTC, BullDog57Rus commented on talk/talk-api.yaml
> -        - name: status
check the change of this parameter

2021-04-07 23:18 UTC, BullDog57Rus commented on talk/talk-api.yaml
> -        - name: phoneNumberId
check the change of this parameter

2021-04-07 23:18 UTC, BullDog57Rus commented on talk/talk-api.yaml
> -        - name: phoneNumber
check the change of this parameter

2021-04-07 23:18 UTC, BullDog57Rus commented on talk/talk-api.yaml
> -        callStatus:
check the change of this parameter

2021-04-08 11:00 UTC, evgeniyp approved these changes

2021-04-09 00:21 UTC, aehrenthal requested changes

2021-04-09 00:21 UTC, aehrenthal commented on talk/talk-api.yaml
> +          description: Caller status.
I think we need to work together with @olyavertwist on some more meaningful descriptions.

2021-04-09 00:21 UTC, aehrenthal commented on talk/talk-api.yaml
> +        - name: participantStatus
How does this one work, if we have many participants? Cant each of them have a different status?

2021-04-09 00:21 UTC, aehrenthal commented on talk/talk-api.yaml
> +              - MY_MISSED
This enum sounds a bit odd to me. Can we maybe call them
- MISSED_BY_ME
- MISSED_BY_TENANT
- NO_ANSWER_BY_ME
- NO_ANSWER_BY_TENANT
What do you think?

2021-04-09 00:21 UTC, aehrenthal commented on talk/talk-api.yaml
> +        - FINISHED
```suggestion
        - ENDED
```
I think in terms of calls "end" is the terminology typically used. It's a minor detail though and does not actually make any difference.

2021-04-09 08:54 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +        - name: participantStatus
there are always many participant. it is just filtering so that any of participant match the filtert

2021-04-09 08:55 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +              - MY_MISSED
I don't like NO_ANSWER_BY because it should filter calls, which was MADE by us and was NOT ANSWERED by the opposite side

2021-04-09 09:32 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +          description: Caller status.
Let us merge it for now, but I will ask Olly to help me with that later :)

2021-04-09 09:43 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +              - MY_MISSED
- MISSED_BY_ME
- MISSED_BY_TENANT
- UNANSWERED_FROM_ME
- UNANSWERED_FROM_TENANT

2021-04-09 09:44 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +        - FINISHED
I think `finished` sound a bit more natural :D

2021-04-09 10:46 UTC, evgeniyp commented on talk/talk-api.yaml
> +              - MY_MISSED
I guess the most meaningful naming would be
MISSED_BY_ME
MISSED_BY_TENANT
UNANSWERED_FROM_ME
UNANSWERED_FROM_TENANT

2021-04-09 10:58 UTC, Zemidar approved these changes

2021-04-09 11:03 UTC, aehrenthal commented on talk/talk-api.yaml
> +              - MY_MISSED
￼￼￼￼￼Agreed about the unanswered! But I am pretty sure it's still "Unanswered by me" and not from.

2021-04-09 12:17 UTC, aehrenthal commented on talk/talk-api.yaml
> +              - MY_MISSED
So the difference between from and by in this situation is the following. If we have two enums
UNANSWERED_BY_ME
UNANSWERED_FROM_ME

Then missed by me would indicate that you received a call from someone and did not answer it. 

But if its unanswered from you, it means that you tried to call someone and that call went unanswered by the other party.

2021-04-09 12:21 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +              - MY_MISSED
yep that is the point. So MISSED_BY_ME is used to indicate that the call is received, but I have not answered
and UNANSWERED_FROM_ME indicates the call, when I called someone and he has not answered

2021-04-09 12:23 UTC, aehrenthal commented on talk/talk-api.yaml
> +              - MY_MISSED
Ah okay, that's the point here. Thanks for clarifying this :) I misunderstood the use-case in that case. Sorry!

2021-04-09 12:23 UTC, aehrenthal approved these changes

2021-04-09 12:24 UTC, evgeniyp commented on talk/talk-api.yaml
> +              - MY_MISSED
Yes, exactly. Applying the filter UNANSWERED_FROM_ME we want to filter calls that unanswered by the other party.

2021-04-09 12:24 UTC, merged