IBA-107: Extend the estimation cost response model by item estimations
inperium-corp/inperium-openapi pull request #203
Opened 2021-04-18 13:00 UTC by eprudnikov

After introducing the add-ons, it makes sense to extended the estimation cost model by the subscription items. The items represent the product subscription item as well as add-ons items. Each of them can have its price and a number of licenses.
The change is still compatible with the current API. It's important to migrate the UI before rolling out non-beta Talk.

2021-04-19 09:40 UTC, olyavertwist requested changes

2021-04-19 09:40 UTC, olyavertwist commented on hub/hub-api.yaml
> +          type: array
description: A list of items.

2021-04-19 09:40 UTC, olyavertwist commented on hub/hub-api.yaml
> +      description: The enumiration defines available subscription item types.
description: The type of subscription item. It indicates whether the item relates to a product or one of its add-ons.

2021-04-19 09:40 UTC, olyavertwist commented on hub/hub-api.yaml
> +      type: object
description: The object helps predict the subscription cost.

2021-04-19 17:12 UTC, eprudnikov commented on hub/hub-api.yaml
> +          type: array
Thank for @olyavertwist for noticing. This and the following corrections are applied 👌

2021-04-19 17:12 UTC, eprudnikov commented on hub/hub-api.yaml
> +      type: object
Fixed ✔

2021-04-19 17:12 UTC, eprudnikov commented on hub/hub-api.yaml
> +      description: The enumiration defines available subscription item types.
Fixed ✔

2021-04-19 19:06 UTC, aehrenthal approved these changes

2021-04-20 16:19 UTC, olyavertwist approved these changes

2021-04-26 09:45 UTC, BullDog57Rus approved these changes

2021-04-26 09:45 UTC, BullDog57Rus commented on hub/hub-api.yaml
> +          deprecated: true
maybe we have to make deprecated properties non-required in the response

2021-05-15 18:14 UTC, merged