Made hub User.id not nullable
inperium-corp/inperium-openapi pull request #205
Opened 2021-04-20 17:36 UTC by evgeniyp

2021-04-20 18:36 UTC, aehrenthal requested changes

2021-04-20 18:36 UTC, aehrenthal commented on hub/hub-api.yaml
> +        - id
```suggestion
        - id
        - email
        - hasVerifiedEmail
        - isAdmin
        - isOwner
```
I think there is a few more fields, but just as a suggestion, let's check all non-null fields and add them here.

2021-04-21 14:09 UTC, evgeniyp commented on hub/hub-api.yaml
> +        - id
Done. Checked with the SQL table specification.

2021-04-21 14:10 UTC, aehrenthal approved these changes

2021-04-21 14:28 UTC, merged