Bugfix/ins 3337
inperium-corp/inperium-openapi pull request #208
Opened 2021-04-29 08:27 UTC by RockMother

Renamed propertyMetadata into dictionaries.
Refactored property configuration.

2021-04-29 13:36 UTC, aehrenthal approved these changes

2021-04-29 14:05 UTC, olyavertwist requested changes
Added comments about descriptions.

2021-04-29 14:05 UTC, olyavertwist commented on sell/sell-api.yaml
> +              type: boolean
description: The true/false parameter indicating if this property supports templates.

2021-04-29 14:05 UTC, olyavertwist commented on sell/sell-api.yaml
> +              type: boolean
description: The true/false parameter indicating if this property supports filtering.

2021-04-29 14:05 UTC, olyavertwist commented on sell/sell-api.yaml
> -  - name: Predefined Metadata
We need to add a Dictionaries tag to Tags.

2021-04-29 15:17 UTC, Zemidar approved these changes

2021-05-04 13:44 UTC, RockMother commented on sell/sell-api.yaml
> +      summary: Retrieve a list of available dictionaries
Done

2021-05-04 13:45 UTC, RockMother commented on sell/sell-api.yaml
> +      description: Use this endpoint to get list of all avaliable dictionaries.
Done

2021-05-04 13:45 UTC, RockMother commented on sell/sell-api.yaml
> +          description: The dictionary has been retrieved. Returns dictionary items.
Done

2021-05-04 19:11 UTC, olyavertwist requested changes
Just one tiny fix - a typo (marka >> marks)

2021-05-04 19:11 UTC, olyavertwist commented on sell/sell-api.yaml
>        type: array
dictionaries/id is removed, so no need to add id to the dictionary object

2021-05-04 19:20 UTC, RockMother commented on sell/sell-api.yaml
> +              description: The parameter marka if this property should be displayed on the object card (e.g., when a user drills down to a company).
Done

2021-05-04 19:26 UTC, olyavertwist approved these changes

2021-05-05 10:45 UTC, merged