[IBA-111] Rework the feature usages interface and add one for the balance charges
inperium-corp/inperium-openapi pull request #215
Opened 2021-05-09 15:39 UTC by eprudnikov

The main reason for the change is the missing tax calculation for the add-ons. Adding the calculation leads to 2 changes in the API:
* From now on, Talk (and other services) cannot post the total feature usage for a tenant/user (e.g. total duration of the calls). It has to post each consumption individually so that we can calculate tax correctly and report the clients about it in all details. 
* An extra end-point to fetch the balance charges to show the clients why the money was taken from their balances. We had to do it anyway, but the extra charge because of the taxes makes it more important.

[Link to the Jira task](https://blackbirdsoftware.atlassian.net/browse/IBA-111).

2021-05-09 16:03 UTC, BullDog57Rus approved these changes

2021-05-09 16:03 UTC, BullDog57Rus commented on hub/hub-api.yaml
> +          description: Additional information about the charge. For example, it can be infortmation about addressee of a call in Inperium Talk.
```suggestion
          description: Additional information about the charge. For example, it can be information about the addressee of a call in Inperium Talk.
```

2021-05-09 16:03 UTC, BullDog57Rus commented on hub/hub-api.yaml
> +      description: The list of available charges.
```suggestion
      description: The list of recorded charges.
```

2021-05-09 18:31 UTC, eprudnikov commented on hub/hub-api.yaml
> +          description: Additional information about the charge. For example, it can be infortmation about addressee of a call in Inperium Talk.
Thanks 👍

2021-05-10 15:24 UTC, aehrenthal requested changes

2021-05-10 15:24 UTC, aehrenthal commented on hub/hub-api.yaml
> +        grossAmount:
As per our call today, this should be changed to netAmount

2021-05-10 15:24 UTC, aehrenthal commented on hub/hub-api.yaml
> +        totalAmount:
If we use netAmount above, I would use grossAmount here for consistency, dont you think?

2021-05-11 16:37 UTC, eprudnikov commented on hub/hub-api.yaml
> +        grossAmount:
Done ✔

2021-05-11 16:38 UTC, eprudnikov commented on hub/hub-api.yaml
> +        totalAmount:
Yes, makes sense 👌

2021-05-11 17:52 UTC, aehrenthal approved these changes

2021-05-13 20:00 UTC, merged