INT-579 Call Forwarding
inperium-corp/inperium-openapi pull request #224
Opened 2021-05-20 16:08 UTC by nurutdinov

2021-05-20 20:03 UTC, BullDog57Rus requested changes

2021-05-20 20:03 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +    BusinessCalendarInterval:
`BusinessHour`?

2021-05-20 20:03 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +        forwardingNumber:
and there will be required properties
number
twentyFourSeven
businessHours

2021-05-21 15:18 UTC, aehrenthal approved these changes

2021-05-21 15:18 UTC, aehrenthal commented on talk/talk-api.yaml
> +          description: If the business hour turned on or not
```suggestion
          description: If the business hour is turned on or not.
```

2021-05-21 18:49 UTC, BullDog57Rus requested changes

2021-05-21 18:49 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +        businessHour:
`businessHours` here, as it is a list

2021-05-21 19:02 UTC, BullDog57Rus approved these changes

2021-05-22 07:28 UTC, merged