INT-580 Number porting
inperium-corp/inperium-openapi pull request #238
Opened 2021-06-02 09:29 UTC by nurutdinov

2021-06-02 13:02 UTC, BullDog57Rus requested changes

2021-06-02 13:02 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +        twilioSid:
let's move all porting-related to a separate model

2021-06-02 13:02 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +        - WAIT
```suggestion
        - WAITING
```

2021-06-02 13:02 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +        - obsId
again, do we need an ID, or an URL is better?

2021-06-02 13:02 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +        - obsId
and also, the object is redundant, as there is only 1 property

2021-06-02 13:02 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +      properties:
allOf, as in portNumber already

2021-06-03 06:33 UTC, nurutdinov commented on talk-number-porting/talk-number-porting-api.yaml
> +        obsId:
Using id we encapsulate file source behind FileProvider.

2021-06-03 07:52 UTC, nurutdinov commented on talk-number-porting/talk-number-porting-api.yaml
> +          $ref: '#/components/schemas/DataFile'
We use DataFile in billing statements and I suggest use it for LOA too to be the same

2021-06-04 16:08 UTC, BullDog57Rus commented on talk-number-porting/talk-number-porting-api.yaml
> +            twilioComment:
let's hide Twilio from the API. So we can name it `responseComment` or something

2021-06-04 16:08 UTC, BullDog57Rus commented on talk-number-porting/talk-number-porting-api.yaml
> +        userComment:
and `requestComment` here

2021-06-04 16:22 UTC, BullDog57Rus approved these changes

2021-06-07 16:14 UTC, olyavertwist reviewed
Thanks for letting me know! I'll check talk-number-porting-api.yaml once I'm done with talk.yaml.
Please feel free to refer to Readme in this repo for tips on how to create beautiful API descriptions. :-)

2021-06-07 16:22 UTC, BullDog57Rus commented on talk-number-porting/talk-number-porting-api.yaml
> +    PortOrderUpdateRequest:
can we use it in `PortOrderRequest` as `allOf`? It might be useful

2021-06-07 16:29 UTC, BullDog57Rus commented on talk-number-porting/talk-number-porting-api.yaml
> +          example: nin::CANCELED,PORTED
add `COMPLETED` or something like that if we have one

2021-06-07 16:29 UTC, BullDog57Rus commented on talk-number-porting/talk-number-porting-api.yaml
> +            - status
no status in `properties`

2021-06-07 16:29 UTC, BullDog57Rus commented on talk-number-porting/talk-number-porting-api.yaml
> +            - status
and let's make comments required also, I think. and just return empty list

2021-06-07 16:29 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +        description: List of phone numbers to create and buy
wrong description. and make sure to add `.` (dot) at the end of all `description`s (but NOT in `summary`s)

2021-06-07 16:29 UTC, BullDog57Rus commented on talk-number-porting/talk-number-porting-api.yaml
> +        address:
maybe we should name it like `addressLine` or `addressLine1` as it it named in all addresses

2021-06-07 16:55 UTC, BullDog57Rus approved these changes

2021-06-07 18:15 UTC, evgeniyp approved these changes

2021-06-07 18:17 UTC, merged