IBA-119: Add TryOutToolActivityRequest
inperium-corp/inperium-openapi pull request #242
Opened 2021-06-07 19:49 UTC by eprudnikov

The PR is about adding a new activity type to Lead Router service API that should be used a lead tried out a free tool.
The firstName and lastName pair are still to be agreed with Shamil. I'd like to keep the naming consistent with other activities.
[Link to the Jira item](https://blackbirdsoftware.atlassian.net/browse/IBA-119).

2021-06-07 19:59 UTC, aehrenthal requested changes

2021-06-07 19:59 UTC, aehrenthal commented on lead-router/lead-router-api.yaml
> +    TryOutToolActivityRequest:
I think we should call it "FreeToolActivityRequest" since we will advertise them as free tools on the website.

2021-06-08 04:49 UTC, eprudnikov commented on lead-router/lead-router-api.yaml
> +    TryOutToolActivityRequest:
Yes, good name, Alex. I just created the PR before we agreed upon the name.

2021-06-08 17:25 UTC, aehrenthal approved these changes

2021-06-08 18:42 UTC, merged