[IBA-117] Extend the BalanceCharge model and create an end-point for BalanceFunds.
inperium-corp/inperium-openapi pull request #251
Opened 2021-06-14 13:22 UTC by eprudnikov

The PR adds more information to the BalanceCharge model to make it more informative for the users. New attributes show not the only amount of money but also what feature and amount of resource are associated with the charge.
Additionally, the PR adds a new end-point allowing to get balance funds. It starts to be important to show that information to users because, after implementing [IBA-117](https://blackbirdsoftware.atlassian.net/browse/IBA-117),  we will have 2 types of funds:

1. The standard ones. Hub creates them automatically basing on the balance configuration. They imply an amount of money the tenant can spend on any metered add-on.
2. The prepaid funds. They imply an amount of resource/feature the tenant can spend. For example, amount of minutes of domestic calls. They can be 
  a. Included in plans. Such funds are created automatically when tenants switch to a paid plan.
  b. Add-ons that tenants can buy at any time in addition to the included funds.

2021-06-15 07:28 UTC, BullDog57Rus approved these changes

2021-06-15 07:28 UTC, BullDog57Rus commented on hub/hub-api.yaml
> +        - name: from
maybe we can use just `date` parameter, which will be implemented with `between::1,2` and others, like we do everywhere

2021-06-15 07:28 UTC, BullDog57Rus commented on hub/hub-api.yaml
> -        - netAmount
isn't it requered still? or it is made nullable now?

2021-06-15 11:34 UTC, olyavertwist requested changes

2021-06-15 11:34 UTC, olyavertwist commented on hub/hub-api.yaml
>          netAmount:
description: The amount without taxes.

2021-06-21 10:30 UTC, eprudnikov commented on hub/hub-api.yaml
> +      description: Use this endpoint to get information about the balance funds of the tenant.
Thank you Olly for all the notes! I updated the file 👍

2021-06-21 11:27 UTC, eprudnikov commented on hub/hub-api.yaml
> +        - name: from
@aehrenthal , will using the `between` operator be handier for you? Both options work for me.
Let me note that `between` doesn't support optional boundaries. If they are needed, the UI should use the `gte` and `lte` operators instead.

2021-06-30 13:22 UTC, olyavertwist approved these changes

2021-06-30 20:33 UTC, merged