Talk descriptions
inperium-corp/inperium-openapi pull request #252
Opened 2021-06-15 09:41 UTC by olyavertwist

I've added descriptions for all talk-api endpoints except for those that are private. Additionally, I've assigned "x-access: private" on the method level (for documentation generation purposes).

With the next PR, I'll update components and their descriptions.

2021-06-15 15:12 UTC, BullDog57Rus requested changes

2021-06-15 15:12 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +    x-access: private
as webhooks are private, let's leave them near their original family :)

2021-06-16 19:04 UTC, olyavertwist commented on talk/talk-api.yaml
> +    x-access: private
For some reason, we had 2 same /webhooks/phoneNumbers/port endpoints. I eliminated one of them and moved the other to its logical "parent" /phoneNumbers.

2021-06-16 20:34 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +        description: In the request body, pass the updated CallChangeRequest.
```suggestion
        content:
        description: In the request body, pass the updated CallChangeRequest.
```

2021-06-16 20:36 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +        description: In the request body, pass the updated CallChangeRequest.
```suggestion
        description: In the request body, pass the updated CallChangeRequest.
        content:
```

2021-06-16 21:02 UTC, BullDog57Rus approved these changes

2021-06-16 21:03 UTC, merged