[INS-3511] [Products] Import does not work
inperium-corp/inperium-openapi pull request #264
Opened 2021-06-29 17:26 UTC by RockMother

Changed parameter for the import. 
Parameters moved from URL to the request body.

2021-06-29 18:51 UTC, aehrenthal approved these changes

2021-06-30 11:24 UTC, olyavertwist requested changes
Really minor changes.

2021-06-30 11:24 UTC, olyavertwist commented on sell/sell-api.yaml
>        description: Use this endpoint to upload a file containing entities to Inperium. For example, you can upload your client data exported from other CRMs and that was previously stored in spreadsh
description: Use this endpoint to upload a file containing entities to Inperium. For example, you can upload your client data exported from other CRMs or data that was previously stored in spreadsheets.

2021-06-30 11:24 UTC, olyavertwist commented on sell/sell-api.yaml
> +      type: object
description: The request object containing import data.

2021-06-30 11:24 UTC, olyavertwist commented on sell/sell-api.yaml
> +                description: The id of the property.
description: The ID of the property.

2021-06-30 11:32 UTC, olyavertwist approved these changes

2021-06-30 11:33 UTC, merged