INT-574 Refactor calls
inperium-corp/inperium-openapi pull request #270
Opened 2021-06-30 16:20 UTC by BullDog57Rus

2021-07-06 08:10 UTC, Onbehalfofme requested changes

2021-07-06 08:10 UTC, Onbehalfofme commented on talk/talk-api.yaml
> +    x-access: private
Add THIS IS INTERNAL ENDPOINT in description for private methods

2021-07-06 08:10 UTC, Onbehalfofme commented on talk/talk-api.yaml
> +      operationId: createParticipant
maybe addParticipant instead of create

2021-07-06 08:10 UTC, Onbehalfofme commented on talk/talk-api.yaml
> +    x-access: private
Add description

2021-07-06 08:10 UTC, Onbehalfofme commented on talk/talk-api.yaml
> +  /webhooks/calls/{id}/participants/{subId}/hang:
`/webhooks/calls/{id}/participants/{userId}/hang:`

2021-07-06 08:10 UTC, Onbehalfofme commented on talk/talk-api.yaml
> +      deprecated: true
Maybe it makes sense to make a description like with the internal endpoint. Something like DEPrecated at the beginning

2021-07-06 08:28 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +      operationId: createParticipant
I try to stick to CRUD naming, just to make it understandable for everyone. And addition of the participant is more about the business logic, but not the REST api

2021-07-09 09:44 UTC, Onbehalfofme approved these changes

2021-07-09 09:56 UTC, merged