INS-3533 Change /export endpoint to public/export endpoint
inperium-corp/inperium-openapi pull request #286
Opened 2021-07-09 11:32 UTC by Zemidar

2021-07-09 11:47 UTC, aehrenthal requested changes

2021-07-09 11:47 UTC, aehrenthal commented on sell/sell-api.yaml
> +  /public/exports/{id}:
Just a quick question, how do we secure this endpoint? Is it through some one time token or some similar method?

2021-07-12 08:13 UTC, Zemidar commented on sell/sell-api.yaml
> +  /public/exports/{id}:
Actually this endpoint already public and not secured(method marked with InperiumPublic annotation).
This PR helps API Gateway with right routing to this public endpoint.

2021-07-12 15:06 UTC, aehrenthal commented on sell/sell-api.yaml
> +  /public/exports/{id}:
After checking the implementation we agreed that it is already pretty secure so we can merge it now but we want to add a token for additional security this month.

2021-07-12 15:06 UTC, aehrenthal approved these changes

2021-07-14 09:46 UTC, merged