INT-589 Call queue
inperium-corp/inperium-openapi pull request #288
Opened 2021-07-12 06:12 UTC by nurutdinov

2021-07-23 20:15 UTC, BullDog57Rus requested changes

2021-07-23 20:15 UTC, BullDog57Rus commented on talk-call-queue/talk-call-queue-api.yaml
> +        - Calls Webhooks
check the tags from the first comment

2021-07-23 20:15 UTC, BullDog57Rus commented on talk-call-queue/talk-call-queue-api.yaml
> +  /webhooks/calls/enqueue/{id}:
and below

2021-07-23 20:15 UTC, BullDog57Rus commented on talk-call-queue/talk-call-queue-api.yaml
> +                QueueTime:
required?

2021-07-23 20:15 UTC, BullDog57Rus commented on talk-call-queue/talk-call-queue-api.yaml
> +        required: true
check everywhere

2021-07-23 20:15 UTC, BullDog57Rus commented on talk-call-queue/talk-call-queue-api.yaml
> +      content: { }
```suggestion
```
and can be used in several requests above

2021-07-23 20:15 UTC, BullDog57Rus commented on talk-call-queue/talk-call-queue-api.yaml
> +        - promptLanguage
you can check, but I think `required` is not needed for properties with `default` value

2021-07-26 06:07 UTC, nurutdinov commented on talk-call-queue/talk-call-queue-api.yaml
> +        - promptLanguage
Yes, agree, but Evgeniy Petukhov added it for UI API interface.

2021-07-27 07:21 UTC, BullDog57Rus approved these changes

2021-07-27 08:45 UTC, merged