INS-3561 Add additional info to Export model
inperium-corp/inperium-openapi pull request #302
Opened 2021-07-22 12:06 UTC by Zemidar

2021-07-22 15:53 UTC, RockMother approved these changes

2021-07-22 16:51 UTC, olyavertwist requested changes

2021-07-22 16:51 UTC, olyavertwist commented on sell/sell-api.yaml
> +          description: The type of export.
description: The type of exported objects.

2021-07-22 16:51 UTC, olyavertwist commented on sell/sell-api.yaml
> +          description: The date the file was uploaded.
description: The date the file was downloaded.

2021-07-22 16:51 UTC, olyavertwist commented on sell/sell-api.yaml
>            description: The count of export file downloads.
description: The number of times the export file was downloaded.

2021-07-22 17:28 UTC, RockMother commented on sell/sell-api.yaml
> +          description: The date the file was uploaded.
Probably should be : The date when data was exported.

2021-07-26 09:47 UTC, olyavertwist approved these changes

2021-07-26 10:00 UTC, merged