[IBA-221] Add the add-ons to the ../plans end-point and make it public
inperium-corp/inperium-openapi pull request #303
Opened 2021-07-25 18:59 UTC by eprudnikov

It is the main part of [task IBA-221](https://blackbirdsoftware.atlassian.net/browse/IBA-221). It makes the existing endpoint `/products/{product}/plans` public (not depending on the tenant context) and puts the add-ons to the response. It allows Talk's price calculator to get all the necessary information to estimate the subscription fee.
Please note that the response is still compatible with the existing UI (the product overview).

2021-07-25 19:05 UTC, eprudnikov commented on hub/hub-api.yaml
> -          description: The object defines what price model the feature has in the plan. Having no model means that the feature is free in the plan.
@olyavertwist , there is a number of other descriptions that do not make sense from OpenAPI perspective. They shouldn't be there by the spec. If you don't use them to generate [developers.inperium.com](https://developers.inperium.com), I'd remove them all because the official tools do not render them anyway.

2021-07-25 19:27 UTC, eprudnikov commented on hub/hub-api.yaml
> +        trialOnly:
Let's add the flag whether the limit is relevant only for the trial subscriptions.

2021-07-25 19:28 UTC, eprudnikov commented on hub/hub-api.yaml
> +        - name: currency
Since we make the end-point not depending on the tenant context, we need to get the currency as the parameter.

2021-07-26 05:51 UTC, BullDog57Rus approved these changes

2021-07-26 11:15 UTC, eprudnikov commented on hub/hub-api.yaml
> -          description: The object defines what price model the feature has in the plan. Having no model means that the feature is free in the plan.
As agreed with Olly, I removed the description because we use it in our doc generator.

2021-07-26 13:48 UTC, olyavertwist requested changes

2021-07-26 13:48 UTC, olyavertwist commented on hub/hub-api.yaml
> +          description: The true/false parameter defining if the limit is relevant in trial mode only.
description: The true/false parameter defining if the limit applies to a trial mode only. For example, during the trial period, users are entitled to a limited number of international calls.

2021-07-26 13:48 UTC, olyavertwist commented on hub/hub-api.yaml
> +          description: List of add-ons associated with the feature.
description: A list of add-ons associated with the feature.

2021-07-26 15:20 UTC, eprudnikov commented on hub/hub-api.yaml
> +          description: The true/false parameter defining if the limit is relevant in trial mode only.
Thank you, Olly, for both corrections. I applied them.
One minor note: having a trial Talk subscription, a tenant has no access to the international calls at all. That's why I used the phone numbers as the example.

2021-07-26 15:43 UTC, merged