Renamed domainName to domainNames
inperium-corp/inperium-openapi pull request #307
Opened 2021-07-29 10:16 UTC by RockMother

Renamed domainName to domains

2021-07-29 14:24 UTC, Zemidar approved these changes

2021-07-29 14:24 UTC, Zemidar commented on sell/sell-api.yaml
> +          deprecated: true
What about add info about deprecation and new implementation to description?

2021-07-30 08:23 UTC, olyavertwist requested changes

2021-07-30 08:23 UTC, olyavertwist commented on sell/sell-api.yaml
> +          description: The website separated by comma.
description: The list of website URLs separated by commas.

2021-07-30 08:29 UTC, RockMother commented on sell/sell-api.yaml
> +          description: The website separated by comma.
Done

2021-07-30 08:29 UTC, RockMother commented on sell/sell-api.yaml
> +          deprecated: true
Nice idea!

2021-07-30 08:36 UTC, olyavertwist approved these changes

2021-07-30 08:37 UTC, merged

2021-08-02 08:04 UTC, eprudnikov commented on sell/sell-api.yaml
> +          deprecated: true
@RockMother , thanks a lot for keeping it compatible!