[IBA-223] Extend the Balance Fund model by expiresIn and unitLabel attributes
inperium-corp/inperium-openapi pull request #313
Opened 2021-08-04 13:21 UTC by eprudnikov

This PR adds the following attributes and parameters:
- GET /funds end-points
  - `isPrepaid`. The parameter helps to filter out so-called prepaid funds, i.e. funds bound with features. For example, SMS package included in a Talk plan or a one-time purchased minute package.
@aehrenthal , please note that there is no parameter filtering the funds by the feature anchor. I expect that it's not so useful in the use. If it is, please let me know, I'll add it.
  - `isExpired`. Since the one-time purchased minute packages have TTL, there will be ones that are already expired. This parameters helps to filter them out.
- BalanceFund
  - `expiresIn`. The attribute defines how many (full) days a tenant has until its prepaid package will expire. For the one-time purchased fund, it implies the expiration time. For the included package, it implies a day when the fund will be reset to its initial value (Hub will refill the same fund instead of creating a new one).
**Note**: returning the full days means that in a day a fund expires, it will return 0. Right after buying 30-days minute package, it will show 29 days. If it's not okay, I can return, for example, the number of minutes until the expiration time so that we can show it more accurately.
@aehrenthal , I can add the exact time (expiresAt) when the expiration will happen, if it will help anywhere.
- Feature
  - `untilLabel`. This attribute defines what the features/add-ons are measured in. It's optional because it's defined only for add-ons (=paid features).

[The Jira item](https://blackbirdsoftware.atlassian.net/browse/IBA-223).

2021-08-04 14:09 UTC, aehrenthal approved these changes

2021-08-04 14:09 UTC, aehrenthal commented on hub/hub-api.yaml
> +        expiresIn:
Should we say expiresInDays or just expiresIn?

2021-08-04 17:32 UTC, olyavertwist requested changes

2021-08-04 17:32 UTC, olyavertwist commented on hub/hub-api.yaml
> +          description: The true/false parameter that identifies if the fund is expired. By default, it returns all funds.
description: The true/false parameter that identifies if the fund has already expired. If the parameter isn't specified, the method returns all funds including expired funds.

2021-08-04 18:49 UTC, eprudnikov commented on hub/hub-api.yaml
> +        expiresIn:
I prefer the current option because it looks more aligned with apiKey.expiresAt, createdAt, updatedAt. The description explains what the unit is. But it's rather a matter of opinion.

2021-08-04 18:53 UTC, eprudnikov commented on hub/hub-api.yaml
> +          description: The true/false parameter that identifies if the fund is expired. By default, it returns all funds.
Thanks, @olyavertwist . Updated ✓

2021-08-04 19:09 UTC, aehrenthal commented on hub/hub-api.yaml
> +        expiresIn:
Sure fine with me

2021-08-05 07:06 UTC, olyavertwist approved these changes

2021-08-05 17:59 UTC, merged