INS-3595 Make every payment independent from invoices
inperium-corp/inperium-openapi pull request #314
Opened 2021-08-04 14:11 UTC by Zemidar

2021-08-04 17:36 UTC, olyavertwist requested changes

2021-08-04 17:36 UTC, olyavertwist commented on sell/sell-api.yaml
> +      description: Use this endpoint to attach payment to invoice.
description: Use this endpoint to attach a payment to the invoice.

2021-08-05 06:54 UTC, RockMother approved these changes

2021-08-30 06:11 UTC, olyavertwist approved these changes

2021-09-02 09:46 UTC, merged