Feature/int 652
inperium-corp/inperium-openapi pull request #316
Opened 2021-08-04 18:44 UTC by Onbehalfofme

2021-08-04 20:43 UTC, BullDog57Rus requested changes

2021-08-04 20:43 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +          description: If set to true, all calls that detected as spam are hanged up immediately.
```suggestion
          description: This parameter defines if spam blocking is enabled.
        hangUpSpamCalls:
          type: boolean
          description: This parameter defines if the incoming calls that are detected as spam should be hanged up immediately.
```

2021-08-04 20:43 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +          description: If set to true, all calls that detected as spam are hanged up immediately.
actually, these properties are not needed for that request, I think. So just use these descriptions for `SpamBlockingSettings` and mark them as `required`

2021-08-06 10:59 UTC, Onbehalfofme commented on talk/talk-api.yaml
> +          description:This parameter defines if the incoming call is detected as spam.
```suggestion
          description: This parameter defines if the incoming call is detected as spam.
```

2021-08-06 19:05 UTC, BullDog57Rus approved these changes

2021-08-06 19:05 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +        blockSpam:
maybe we can remove them from this response?

2021-08-07 13:16 UTC, merged