INT-769  Fix null values in column 'Phone number owner' in 'Call History' table
inperium-corp/inperium-openapi pull request #347
Opened 2021-09-13 16:19 UTC by nurutdinov

2021-09-13 16:23 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +        - name: ownerReferenceId
I think it will be hard to both use it from the FE side, and implement it from the BE side. Let's add a discriminator?

2021-09-14 13:21 UTC, olyavertwist requested changes
I've prepared descriptions. Thanks in advance!

2021-09-14 13:21 UTC, olyavertwist commented on talk/talk-api.yaml
> +      type: object
description: The object contains information about the phone number owner that is submitted to Inperium API.

2021-09-14 13:21 UTC, olyavertwist commented on talk/talk-api.yaml
> +      allOf:
description: The object describes the phone number assignment.

2021-09-14 13:21 UTC, olyavertwist commented on talk/talk-api.yaml
> +              type: string
description: The owner's name.

2021-09-14 13:21 UTC, olyavertwist commented on talk/talk-api.yaml
> +      type: string
description: The phone number can be assigned to an Inperium user or functionality such as a call queue. This is enum parameter.

2021-09-15 13:32 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +        - name: ownerReferenceId
ah lol it was not :D

2021-09-16 08:43 UTC, olyavertwist approved these changes
Thanks! :-)

2021-09-17 16:49 UTC, evgeniyp approved these changes

2021-09-28 12:21 UTC, merged