INT-618 Clean up API
inperium-corp/inperium-openapi pull request #348
Opened 2021-09-14 07:55 UTC by Onbehalfofme

2021-09-17 08:21 UTC, BullDog57Rus reviewed
For me looks fine. I let @nurutdinov and @ro-mgh decide because number porting should fit the adapted API

2021-09-17 09:59 UTC, ro-mgh approved these changes

2021-09-21 16:05 UTC, olyavertwist requested changes

2021-09-21 16:05 UTC, olyavertwist commented on talk/talk-api.yaml
> +      type: object
description: The object is used to modify phone number settings.

2021-09-22 14:12 UTC, olyavertwist approved these changes

2021-09-28 14:08 UTC, merged