INT-650 Adjust API for new renamed entities
inperium-corp/inperium-openapi pull request #349
Opened 2021-09-16 10:12 UTC by Onbehalfofme

2021-09-16 10:26 UTC, BullDog57Rus requested changes

2021-09-16 10:26 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +                TwilioSid:
callbacks from Twilio, revert :)

2021-09-16 10:26 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +                TwilioSid:
callbacks from Twilio, revert :)

2021-09-16 10:26 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +      summary: Retrieve tenant
```suggestion
      summary: Retrieve tenants
```

2021-09-16 10:26 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +          description: The tenant has been retrieved. Returns tenant.
```suggestion
          description: The tenants have been retrieved. Returns tenants.
```

2021-09-16 10:26 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +      summary: List user account
```suggestion
      summary: List user accounts
```

2021-09-16 10:26 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +        - Tenant
```suggestion
        - Tenants
```
all tags are plural

2021-09-16 10:26 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +  /tenant:
```suggestion
  /tenants:
```
all endpoints are plural too

2021-09-16 10:26 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +                $ref: '#/components/schemas/UserAccount'
let's discuss that, but I think we have to generify /tenants and /users, so maybe the list should not be return in both of them

2021-09-16 10:26 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +        - TwilioSid
all twilio models should be reverted

2021-09-16 10:26 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +        userId:
deprecate the old one and add a new one

2021-09-16 12:38 UTC, Onbehalfofme commented on talk/talk-api.yaml
> +                $ref: '#/components/schemas/UserAccount'
I agree that we should get rid of UserAccounts, but then, if we assume that there is only one user or tenant we should leave descriptions and endpoints.

2021-09-16 15:58 UTC, BullDog57Rus requested changes

2021-09-16 15:58 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +  /tenants/spamBlocking:
```suggestion
  /tenants/current/spamBlocking:
```

2021-09-16 15:58 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +      summary: List spam blocking settings
```suggestion
      summary: Retrieve current tenant's spam blocking settings
```

2021-09-16 15:58 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +      operationId: getSpamBlocking
```suggestion
      operationId: getCurrentSpamBlocking
```

2021-09-16 15:58 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +      summary: Update spam blocking settings
```suggestion
      summary: Update current tenant's spam blocking settings
```

2021-09-16 15:58 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +          description: The spam blocking settings have been updated. Returns spam blocking settings.
```suggestion
          description: The spam blocking settings have been updated. Returns spam blocking settings.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpamBlockingSettings'
```

2021-09-16 15:58 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +    UserAccount:
just User is ok, I think

2021-09-16 16:42 UTC, BullDog57Rus approved these changes

2021-09-16 20:08 UTC, olyavertwist commented
Guys, I have a question for you because I'm not sure what is the best solution here. I see that you mark some methods "deprecated". Do you want them to be visible in the API docs? If you want to hide them, please add 'x-access: private'. If they must be visible, please DM me & we'll figure out how to show them properly.

2021-09-16 20:15 UTC, olyavertwist requested changes

2021-09-16 20:15 UTC, olyavertwist commented on talk/talk-api.yaml
> +      summary: Retrieve current tenant's spam blocking settings
```suggestion
      summary: Retrieve spam blocking settings
```

2021-09-16 20:15 UTC, olyavertwist commented on talk/talk-api.yaml
> +      description: Use this endpoint to retrieve spam blocking settings on the tenant level.
```suggestion
      description: Use this endpoint to retrieve spam blocking settings for a current tenant.
```

2021-09-16 20:15 UTC, olyavertwist commented on talk/talk-api.yaml
> +      summary: Update current tenant's spam blocking settings
```suggestion
      summary: Update spam blocking settings
```

2021-09-16 20:15 UTC, olyavertwist commented on talk/talk-api.yaml
> +      description: Use this endpoint to update spam blocking settings configured on the tenant level.
```suggestion
      description: Use this endpoint to update spam blocking settings for a current tenant.
```

2021-09-16 20:15 UTC, olyavertwist commented on talk/talk-api.yaml
> +      summary: Retrieve current user configuration.
```suggestion
      summary: Retrieve configuration
```

2021-09-16 20:15 UTC, olyavertwist commented on talk/talk-api.yaml
> +          description: The current user configuration has been retrieved. Returns current user configuration.
```suggestion
          description: The current user's configuration has been retrieved. Returns current user's configuration.
```

2021-09-16 20:15 UTC, olyavertwist commented on talk/talk-api.yaml
> +      summary: Update current user configuration
```suggestion
      summary: Update configuration
```

2021-09-16 20:15 UTC, olyavertwist commented on talk/talk-api.yaml
> +      description: Use this endpoint to modify and overwrite current user configuration.
```suggestion
      description: Use this endpoint to modify and overwrite the current user's configuration.
```

2021-09-16 20:15 UTC, olyavertwist commented on talk/talk-api.yaml
> +        description: In the request body, pass the UserRequest object.
```suggestion
        description: In the request body, pass the UserConfigurationRequest object.
```

2021-09-17 08:25 UTC, nurutdinov approved these changes

2021-09-17 11:42 UTC, olyavertwist requested changes

2021-09-17 11:42 UTC, olyavertwist commented on talk/talk-api.yaml
> +      summary: Update current tenant's spam blocking settings
```suggestion
        - Tenants
      summary: Update spam blocking settings
```

2021-09-17 11:42 UTC, olyavertwist commented on talk/talk-api.yaml
> +      Inperium Talk enables users to get tenant settings.(Deprecated)
```suggestion
      Currently, these endpoints are deprecated. Please leverage endpoints from the `Tenants` section.
```

2021-09-17 11:42 UTC, olyavertwist commented on talk/talk-api.yaml
>        Inperium Talk enables users to get tenant settings.
```suggestion
      Inperium Talk enables users to manage common tenant settings such as spam blocking.
```

2021-09-17 11:42 UTC, olyavertwist commented on talk/talk-api.yaml
> +  - name: Tenant settings
```suggestion
  - name: Tenant Settings
```

2021-09-17 11:42 UTC, olyavertwist commented on talk/talk-api.yaml
> +      Each user has a unique profile that contains information about the default contact number, forwarding options, and many more.(Deprecated)
```suggestion
  - name: User Settings
    description: |
      These endpoints are now deprecated. Please leverage endpoints from the 'Users' section.
```

2021-09-17 11:48 UTC, olyavertwist approved these changes

2021-09-20 13:22 UTC, merged