[INS-3759] [Activities] Refactoring BE part of actives for the new UI.
inperium-corp/inperium-openapi pull request #376
Opened 2021-10-19 14:44 UTC by RockMother

2021-11-02 09:53 UTC, RockMother commented on sell/sell-api.yaml
> +        - name: activityType
Done

2021-11-02 09:53 UTC, RockMother commented on sell/sell-api.yaml
> +          description: The type of user activity. One of `NOTE`, `MEETING`, `CALL`, `TASK`, etc.
It's no possible, because types will be editable by user.

2021-11-02 09:55 UTC, RockMother commented on sell/sell-api.yaml
>      ActivityRequest:
Done

2021-11-02 12:47 UTC, Zemidar approved these changes

2021-11-02 22:26 UTC, aehrenthal requested changes

2021-11-02 22:26 UTC, aehrenthal commented on sell/sell-api.yaml
> +        - name: associatedUserId
```suggestion
        - name: associatedUserIds
```
To match with the current Activity entity

2021-11-02 22:26 UTC, aehrenthal commented on sell/sell-api.yaml
> +        - name: eventType
Did you push your latest changes @RockMother? I see this change in the Activity entity itself but not in the /activities API filters

2021-11-02 22:26 UTC, aehrenthal commented on sell/sell-api.yaml
>          - name: associatedContactId
```suggestion
        - name: associatedContactIds
```
To match with the current Activity entity. Same for the other fields

2021-11-03 08:30 UTC, RockMother commented on sell/sell-api.yaml
>          - name: associatedContactId
Probably here should be singular because we are looking for the one associate contacted, no?

2021-11-03 08:30 UTC, RockMother commented on sell/sell-api.yaml
> +        - name: associatedUserId
Probably here should be singular because we are looking for the one associate user id, no?

2021-11-15 14:00 UTC, olyavertwist reviewed
Created descriptions

2021-11-15 14:00 UTC, olyavertwist commented on sell/sell-api.yaml
> +          type: boolean
description: The parameter defines if the activity type is built-in (`FALSE`) or created by the user (`TRUE`).

2021-11-19 13:58 UTC, olyavertwist reviewed
Added descriptions

2021-11-19 13:58 UTC, olyavertwist commented on sell/sell-api.yaml
> +      description: Use this endpoint to create a new activity type.
```suggestion
      description: Use this endpoint to create a new custom activity type.
```

2021-11-19 13:58 UTC, olyavertwist commented on sell/sell-api.yaml
> +      summary: Update an activity type.
```suggestion
      summary: Update an activity type
```

2021-11-19 13:58 UTC, olyavertwist commented on sell/sell-api.yaml
> +      description: Use this endpoint to modify an existing activity type.
```suggestion
      description: Use this endpoint to modify an existing activity type. Provide the activity type ID in the path.
```

2021-11-19 13:58 UTC, olyavertwist commented on sell/sell-api.yaml
> +          format: uuid
description: The activity type ID.

2021-11-19 13:58 UTC, olyavertwist commented on sell/sell-api.yaml
> +        name:
description: The activity type title.

2021-11-19 13:58 UTC, olyavertwist commented on sell/sell-api.yaml
> +        icon:
description: The icon to be used in the Activity timeline.

2021-11-19 13:58 UTC, olyavertwist commented on sell/sell-api.yaml
> +          type: boolean
description: The parameter defines if this activity type is obsolete and inactive (TRUE) or active (FALSE).

2021-11-19 13:58 UTC, olyavertwist commented on sell/sell-api.yaml
> +          type: boolean
description: The parameter defines if this activity type is obsolete and inactive (TRUE) or active (FALSE).

2021-11-19 13:58 UTC, olyavertwist commented on sell/sell-api.yaml
> +      type: object
description: The object describes a category the activity falls into.

2021-12-01 11:20 UTC, RockMother commented on sell/sell-api.yaml
> +          description: The type of activity. USER or EVENT.
Done

2021-12-01 11:21 UTC, RockMother commented on sell/sell-api.yaml
> +      summary: List of ActivityType objects
Done

2021-12-01 11:22 UTC, RockMother commented on sell/sell-api.yaml
> +          description: The specify date due activity should be done.
Done

2021-12-01 11:22 UTC, RockMother commented on sell/sell-api.yaml
> +          description: Shows if activity is done.
Done

2021-12-01 11:23 UTC, RockMother commented on sell/sell-api.yaml
> +              description: The specify date due activity should be done.
Done

2021-12-01 11:23 UTC, RockMother commented on sell/sell-api.yaml
> +      type: object
Done

2021-12-01 11:24 UTC, RockMother commented on sell/sell-api.yaml
> +      description: Use this endpoint to create a new activity type.
Done

2021-12-01 11:25 UTC, RockMother commented on sell/sell-api.yaml
> +      description: Use this endpoint to modify an existing activity type.
Done

2021-12-01 11:25 UTC, RockMother commented on sell/sell-api.yaml
> +          type: boolean
Done

2021-12-01 11:25 UTC, RockMother commented on sell/sell-api.yaml
> +          type: string
Done

2021-12-01 11:25 UTC, RockMother commented on sell/sell-api.yaml
> +          type: string
Done

2021-12-01 11:25 UTC, RockMother commented on sell/sell-api.yaml
> +          type: string
Done

2021-12-01 11:27 UTC, RockMother commented on sell/sell-api.yaml
> +          format: uuid
Done

2021-12-01 11:27 UTC, RockMother commented on sell/sell-api.yaml
> +        name:
Done

2021-12-01 11:27 UTC, RockMother commented on sell/sell-api.yaml
> +        icon:
Done

2021-12-01 11:27 UTC, RockMother commented on sell/sell-api.yaml
> +          type: boolean
Done

2021-12-01 11:27 UTC, RockMother commented on sell/sell-api.yaml
> +      type: object
Done

2021-12-01 11:42 UTC, olyavertwist reviewed
Minor updates needed

2021-12-01 11:42 UTC, olyavertwist commented on sell/sell-api.yaml
>        description: The ActivityRequest object is submitted to Inperium API to add or modify activities.
```suggestion
      description: The object is submitted to Inperium API when you add or modify user activities.
```

2021-12-01 11:42 UTC, olyavertwist commented on sell/sell-api.yaml
> +          description: The date by which activity should be done.
```suggestion
          description: The date by which the activity should be done.
```

2021-12-01 11:42 UTC, olyavertwist commented on sell/sell-api.yaml
>        description: The array of Activity objects with paging and sorting information.
```suggestion
      description: Activities with paging and sorting information.
```

2021-12-01 11:42 UTC, olyavertwist commented on sell/sell-api.yaml
> +              description: The date by which activity should be done.
```suggestion
              description: The date by which the activity should be done.
```

2021-12-02 13:38 UTC, RockMother commented on sell/sell-api.yaml
>        description: The ActivityRequest object is submitted to Inperium API to add or modify activities.
Done

2021-12-02 13:39 UTC, RockMother commented on sell/sell-api.yaml
> +          description: The date by which activity should be done.
Done

2021-12-02 13:39 UTC, RockMother commented on sell/sell-api.yaml
>        description: The array of Activity objects with paging and sorting information.
Done

2021-12-02 13:39 UTC, RockMother commented on sell/sell-api.yaml
> +              description: The date by which activity should be done.
Done

2021-12-03 16:11 UTC, aehrenthal approved these changes

2021-12-03 19:57 UTC, merged