Feature/ins 3749
inperium-corp/inperium-openapi pull request #394
Opened 2021-11-01 14:33 UTC by Zemidar

2021-11-02 07:17 UTC, ShakirovaE commented on sell/sell-api.yaml
> +          description: The olanned payments have been retrieved. Returns ExtendedPlannedPayment.
```suggestion
          description: The planned payments have been retrieved. Returns InvoicePlannedPayments object.
```

2021-11-02 07:28 UTC, ShakirovaE commented on sell/sell-api.yaml
> +      description: The payment paln for a invoice. For each invoice, a manager can suggest a payment schedule and split the total amount into several payments.
```suggestion
      description: The payment plan for a invoice. For each invoice, a manager can suggest a payment schedule and split the total amount into several payments.
```

2021-11-02 07:49 UTC, ShakirovaE approved these changes

2021-11-02 14:45 UTC, olyavertwist requested changes

2021-11-02 14:45 UTC, olyavertwist commented on sell/sell-api.yaml
>        Inperium Sell enables users to create professional-looking invoices and process them within CRM.
```suggestion
      Inperium Sell enables users to create professional-looking invoices and process them within CRM. On top of that, Inperium Sell allows sharing invoices with customers through public URLs. It means you can send an invoice link to your clients, they will follow this link, and review the invoice in the browser.
```

2021-11-02 14:45 UTC, olyavertwist commented on sell/sell-api.yaml
> +      summary: List of planned payments
```suggestion
      summary: List planned payments
```

2021-11-02 14:45 UTC, olyavertwist commented on sell/sell-api.yaml
> +      description: Use this endpoint to get the list of payment plans for the invoices. For each invoice, you can set up a payment plan, for example, to split the invoice into several payments. This
```suggestion
      description: Use this endpoint to get the list of upcoming payments according to a specified payment plan. For each invoice, you can set up a payment plan, for example, to split the invoice into several payments. This endpoint supports sorting and paging.
```

2021-11-02 14:45 UTC, olyavertwist commented on sell/sell-api.yaml
> +          description: The payment plan for a invoice. For each invoice, a manager can suggest a payment schedule and split the total amount into several payments.
```suggestion
          description: The payment plan for an invoice. For each invoice, a manager can suggest a payment schedule and split the total amount into several payments.
```

2021-11-02 14:45 UTC, olyavertwist commented on sell/sell-api.yaml
> +              type: string
description: The invoice title.

2021-11-02 14:45 UTC, olyavertwist commented on sell/sell-api.yaml
> +      description: The payment paln for a invoice. For each invoice, a manager can suggest a payment schedule and split the total amount into several payments.
```suggestion
      description: The payment plan for an invoice. For each invoice, a manager can suggest a payment schedule and split the total amount into several payments.
```

2021-11-02 14:45 UTC, olyavertwist commented on sell/sell-api.yaml
> +              description: The list of payment plans enabled for the invoice.
```suggestion
              description: The list of payments planned according to a payment plan.
```

2021-11-04 08:29 UTC, RockMother commented on sell/sell-api.yaml
> +  /invoices/plannedPayments:
Nice name!

2021-11-04 09:08 UTC, olyavertwist approved these changes
I have one tiny comment for the sake of beautiful API documentation:-)

2021-11-04 09:08 UTC, olyavertwist commented on sell/sell-api.yaml
> +      summary: Retrieve an invoice
```suggestion
      summary: Generate a public invoice
```
I'm afraid we have to rename the summary otherwise it will show up a duplicate entry in API docs (we already have another 'Retrieve an invoice' with /invoices/{id})

2021-11-09 06:22 UTC, Zemidar commented on sell/sell-api.yaml
> +      summary: Retrieve an invoice
Done

2021-11-15 11:51 UTC, olyavertwist approved these changes
Could you please fix these two descriptions for me? It was actually my grammar mistake :-(

2021-11-15 11:51 UTC, olyavertwist commented on sell/sell-api.yaml
> +      description: The object contains information about the company as it will appear in the quote/invoice. Unlike the 'company' object, it has less parameters.
```suggestion
      description: The object contains information about the company as it will appear in the quote/invoice. Unlike the 'company' object, it has fewer parameters.
```

2021-11-15 11:51 UTC, olyavertwist commented on sell/sell-api.yaml
> +      description: The object contains information about the contact as it will appear in the quote/invoice. Unlike the 'contact' object, it has less parameters.
```suggestion
      description: The object contains information about the contact as it will appear in the quote/invoice. Unlike the 'contact' object, it has fewer parameters.
```

2021-11-16 14:15 UTC, Zemidar commented on sell/sell-api.yaml
> +      description: The object contains information about the contact as it will appear in the quote/invoice. Unlike the 'contact' object, it has less parameters.
done

2021-11-17 13:19 UTC, olyavertwist approved these changes

2021-11-22 15:49 UTC, merged