INT-1070 Implement the availability settings menu item and page
inperium-corp/inperium-openapi pull request #414
Opened 2021-11-26 09:40 UTC by nurutdinov

2021-11-26 19:02 UTC, olyavertwist requested changes
Added descriptions.

2021-11-26 19:02 UTC, olyavertwist commented on talk/talk-api.yaml
> +      type: object
description: Facilitates filtering.

2021-11-27 07:56 UTC, BullDog57Rus requested changes

2021-11-27 07:56 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +        status:
are you sure that you want to return all user information from hub just to retrieve user configuration about statuses and call forwarding?

2021-11-29 13:30 UTC, nurutdinov commented on talk/talk-api.yaml
> +        status:
I've added list of fields to request, see diff

2021-12-01 11:05 UTC, olyavertwist approved these changes
Left a small suggestion and also wrote you personally about the trace HTTP verb

2021-12-01 16:56 UTC, BullDog57Rus approved these changes

2021-12-03 09:36 UTC, merged