INS-3753 [Invoice] Delete invoice endpoint
inperium-corp/inperium-openapi pull request #416
Opened 2021-11-29 12:44 UTC by ShakirovaE

2021-11-30 19:13 UTC, Zemidar approved these changes

2021-11-30 19:13 UTC, Zemidar commented on sell/sell-api.yaml
> +      summary: Delete an invoices
```suggestion
      summary: Delete the invoice
```

2021-11-30 19:13 UTC, Zemidar commented on sell/sell-api.yaml
> +      description: Use this endpoint to remove an invoice.
```suggestion
      description: Use this endpoint to remove invoice by id.
```

2021-12-01 10:13 UTC, olyavertwist requested changes
Small update for better user experience

2021-12-01 10:13 UTC, olyavertwist commented on sell/sell-api.yaml
> +      description: Use this endpoint to remove invoice by id.
```suggestion
      description: Use this endpoint to remove the invoice by its ID. Note that the payments associated with this invoice remain in the system.
```

2021-12-01 10:38 UTC, olyavertwist approved these changes

2021-12-02 12:42 UTC, merged