[INS-3759] [Activities] Refactoring BE part of actives for the new UI…
inperium-corp/inperium-openapi pull request #435
Opened 2021-12-07 19:58 UTC by RockMother

…. (#376)

2021-12-07 20:41 UTC, olyavertwist commented
Please update the ActivtyTypes tag description as well:

 - name: ActivityTypes
    description: |
      Depending on the type, activities are either generated automatically or created by users. `EVENT`-based activities (such as when you add a new company or delete a contact) or `MESSAGE` activities (email activity in the Message Center) are logged automatically. The`User`-based activities are added to the timeline by users themselves, for example, when users add notes and tasks.

2021-12-07 20:44 UTC, olyavertwist requested changes
I prepared a more detailed description of activity types.

2021-12-07 20:44 UTC, olyavertwist commented on sell/sell-api.yaml
> +          description: The type of activity. Is one of `USER`, `EVENT` or 'MESSAGE'. Activities can be system-generated (events) or created by user.
```suggestion
          description: The type of activity. Is one of `USER`, `EVENT` or `MESSAGE`.  The `EVENT` activity is system-generated (e.g., when a company is created), the `USER` activities are initialized by an Inperium user (e.g., a new task), the `MESSAGE` activity covers all communication through the Message Center.
```

2021-12-08 07:43 UTC, ShakirovaE commented on sell/sell-api.yaml
> +    MessageActivity:
Comment for string 4266.
Do wee need to remove "MESSAGE_SENT" from enum?

2021-12-08 09:17 UTC, RockMother commented on sell/sell-api.yaml
> +    MessageActivity:
Good point.

2021-12-08 09:33 UTC, ShakirovaE approved these changes

2021-12-08 09:43 UTC, olyavertwist approved these changes

2021-12-08 09:43 UTC, olyavertwist commented on sell/sell-api.yaml
> +      Depending on the type, activities are either generated automatically or created by users. EVENT-based activities (such as when you add a new company or delete a contact) or MESSAGE activities (
```suggestion
      Depending on the type, activities are either generated automatically or created by users. The `EVENT`-based activities (such as when you add a new company or delete a contact) or the `MESSAGE` activities (email activity in the Message Center) are logged automatically. The `USER`-based activities are added to the timeline by users themselves, for example, when users add notes and tasks.
```

2021-12-08 09:47 UTC, merged