INT-1106  Contact groups in mobile and web UI
inperium-corp/inperium-openapi pull request #447
Opened 2021-12-14 12:32 UTC by Onbehalfofme

2021-12-14 15:11 UTC, nurutdinov requested changes

2021-12-14 15:11 UTC, nurutdinov commented on talk/talk-api.yaml
> +          description: The parameter marks if this contact is favovurite for the user.
```suggestion
          description: The parameter marks if this contact is favourite for the user.
```

2021-12-14 15:11 UTC, nurutdinov commented on talk/talk-api.yaml
> +          description: The parameter marks if this contact is favovurite for the user.
```suggestion
          description: The parameter marks if this contact is favourite for the user.
```

2021-12-14 15:11 UTC, nurutdinov commented on talk/talk-api.yaml
> +              enum:
Let's move it to a separate object

2021-12-14 15:11 UTC, nurutdinov commented on talk/talk-api.yaml
> +          enum:
Let's move it to a separate object

2021-12-15 08:42 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +        contactType:
just `type`

2021-12-15 08:42 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +        favourite:
required both?

2021-12-16 09:22 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +        contactType:
not fixed

2021-12-17 08:47 UTC, BullDog57Rus approved these changes

2021-12-20 13:08 UTC, olyavertwist approved these changes

2021-12-21 11:10 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +      discriminator:
I think moving discriminator on the contact level will also solve the problem of statuses for internal contacts

2021-12-22 15:48 UTC, olyavertwist commented
`
favourite:
              type: boolean
              description: The parameter marks if this contact is favourite for the user.
`

Hey, I'm wondering what's better 'favorite' or 'favourite'? Both spellings are correct but the one without U (favorite) is more common in the US. At the same time, Apple prefers 'favourite' while Microsoft says 'favorite'. 

In any case, we should use the same spelling here in API and in UI. @nurutdinov What do you plan on using in UI? In Confluence article. I see 'favorites' and would personally prefer it too but it's not really a bit deal. (https://blackbirdsoftware.atlassian.net/wiki/spaces/IN/pages/1985871972/Contacts+List)

2021-12-22 15:59 UTC, olyavertwist requested changes

2021-12-22 15:59 UTC, olyavertwist commented on talk/talk-api.yaml
> +              description: The name for the phone number.
```suggestion
              description: The phone number title.
```

2021-12-22 15:59 UTC, olyavertwist commented on talk/talk-api.yaml
> +              description: The city where phone number resides.
```suggestion
              description: The city where the phone number resides.
```

2021-12-22 15:59 UTC, olyavertwist commented on talk/talk-api.yaml
> +              description: The state where phone number resides.
```suggestion
              description: The state where the phone number resides.
```

2021-12-22 15:59 UTC, olyavertwist commented on talk/talk-api.yaml
> +      description: The user state in the system. The status is displayed to other users. This is enum parameter.
```suggestion
      description: The user's state in the system. The status is displayed to other users. This is enum parameter.
```

2021-12-22 15:59 UTC, olyavertwist commented on talk/talk-api.yaml
> +      description: The type of contact info.
```suggestion
      description: The type of contact info. This is enum parameter.
```

2021-12-22 17:05 UTC, nurutdinov commented
>

2021-12-22 17:09 UTC, nurutdinov commented
@olyavertwist, yes, Evgeni used 'favorite' in the design too. @Onbehalfofme let's use it everywhere.

2021-12-23 10:46 UTC, Onbehalfofme commented on talk/talk-api.yaml
> +          $ref: "#/components/schemas/ContactType"
User status contains time which has to be available to the user itself.

2021-12-27 07:32 UTC, nurutdinov approved these changes

2021-12-27 09:19 UTC, olyavertwist approved these changes

2021-12-27 09:19 UTC, merged