INT-303 INT-301 Allow to purchase multiple phone numbers at once
inperium-corp/inperium-openapi pull request #94
Opened 2020-11-08 20:23 UTC by BullDog57Rus

Add the PhoneNumber.Name field

2020-11-09 09:13 UTC, evgeniyp requested changes

2020-11-09 09:13 UTC, evgeniyp commented on talk/talk-api.yaml
> +          $ref: '#/components/schemas/PhoneNumberAssigmentType'
```suggestion
          $ref: '#/components/schemas/PhoneNumberAssignmentType'
```

2020-11-09 09:55 UTC, evgeniyp requested changes

2020-11-09 09:55 UTC, evgeniyp commented on talk/talk-api.yaml
> +    PhoneNumberAssigmentType:
```suggestion
    PhoneNumberAssignmentType:
```

2020-11-09 13:51 UTC, aehrenthal approved these changes

2020-11-09 13:51 UTC, aehrenthal commented on talk/talk-api.yaml
> +        timeout:
I think a description of this field would be helpful

2020-11-10 14:35 UTC, BullDog57Rus commented on talk/talk-api.yaml
> +        timeout:
done :)

2020-11-10 14:38 UTC, evgeniyp approved these changes

2020-11-10 14:39 UTC, merged