Feature/INA-137
inperium-corp/inperium-openapi pull request #99
Opened 2020-11-12 19:58 UTC by aehrenthal

This pull request includes additional hub API improvements to make the user account creation process more seamless.

2020-11-12 20:39 UTC, BullDog57Rus commented on hub/hub-api.yaml
> +      description: Use this endpoint to add a new user to Inperium. Provide basic information about the new user. They will receieve an invitation by email.
```suggestion
      description: Use this endpoint to add a new user to Inperium. Provide basic information about the new user.
```
it is not only invite

2020-11-12 20:39 UTC, BullDog57Rus commented on hub/hub-api.yaml
> +          "*/*":
```suggestion
          application/json:
```

2020-11-12 20:39 UTC, BullDog57Rus commented on hub/hub-api.yaml
> +                - INSUFFICIENT_PERMISSIONS
where do u need it? I think 403 Forbidden in made for this :)

2020-11-12 20:39 UTC, BullDog57Rus commented on hub/hub-api.yaml
> +        email:
why do we need both email and oneTimeCode? the email to find the user?

2020-11-12 20:40 UTC, BullDog57Rus commented on hub/hub-api.yaml
> +                - INSUFFICIENT_PERMISSIONS
I just think that currently, we add this if the FE needs to know anything about the exception

2020-11-12 22:19 UTC, BullDog57Rus commented on hub/hub-api.yaml
> +        isAdmin:
```suggestion
        admin:
```
we have a boolean getter prefix "is", so not to have isIsAdmin we can do this :)

2020-11-13 00:33 UTC, aehrenthal commented on hub/hub-api.yaml
> +          "*/*":
Done

2020-11-13 00:33 UTC, aehrenthal commented on hub/hub-api.yaml
> +                - INSUFFICIENT_PERMISSIONS
Done

2020-11-13 00:33 UTC, aehrenthal commented on hub/hub-api.yaml
> +        email:
Just for security, that way you need to know the user email + their oneTimeCode and cannot just "guess" it.

2020-11-13 00:33 UTC, aehrenthal commented on hub/hub-api.yaml
> +        isAdmin:
I wanted to change this one too, but sell and the starter library use this one too and I wanted to keep my changes in this PR as small as possible (given that its already quite big)

2020-12-02 16:05 UTC, RockMother requested changes

2020-12-02 16:05 UTC, RockMother commented on hub/hub-api.yaml
> +              $ref: "#/components/schemas/Id"
Not sure that we really need to use tenantId here. Probably it's a potential security issue.

2020-12-03 19:55 UTC, aehrenthal commented on hub/hub-api.yaml
> +              $ref: "#/components/schemas/Id"
We just removed it, thanks. It was checked in the code, but it's still safer not to expose it on the API.

2020-12-03 19:57 UTC, BullDog57Rus approved these changes

2020-12-03 19:58 UTC, merged